name = "headacher"
main = "worker/index.ts"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "headacher-production"
database_id = "c0e1170f-a16c-4d93-abbe-e0e4192042ae"
preview_database_id = "headacher"

# JWT Secret Key (generate with: wrangler secret put JWT_SECRET_KEY)
# For production, use: wrangler secret put JWT_SECRET_KEY
# [vars]
# JWT_SECRET_KEY = "your-development-jwt-secret-key-here-replace-with-proper-secret"

[[routes]]
pattern = "headacher.sirsean.me"
custom_domain = true

[observability.logs]
enabled = true

